{
    "name": "Deploy",
    "on": {
        "push": {
            "branches": ["prod"],
        },
    },
    "jobs": {
        "deploy": {
            "runs-on": "ubuntu-latest",
            "steps": [
                { "uses": "actions/checkout@v4" },
                { "uses": "pnpm/action-setup@v4" },
                { "uses": "actions/setup-node@v4", "with": { "node-version": 20, "cache": "pnpm" } },
                { "run": "pnpm install" },
                { "run": "pnpm build" },
                {
                    "uses": "JamesIves/github-pages-deploy-action@v4.4.1",
                    "with": { "branch": "gh-pages", "folder": "dist" },
                },
            ],
        },
    },
}
